### ISSUE TITLE
Рефлексия - зло

### ISSUE THREAD

**Issue by Red-Cat-Fat** [Walter-Sparrow/awesomeClicker#1]
https://github.com/Walter-Sparrow/awesomeClicker/blob/3a429422949f4d7be3686787cb0832e9db941d6e/Assets/Scripts/ClickEvent.cs#L10

**Comment by Walter-Sparrow** [comment]
https://github.com/Walter-Sparrow/awesomeClicker/commit/54d82208e259520493b412db1984ea51ece2e450
Исправлена эта ошибка и Issue#2

**Comment by Red-Cat-Fat** [comment]
А зачем ты сделал её public?

**Comment by Red-Cat-Fat** [comment]
И вообще это относится ко всему проекту

**Comment by Walter-Sparrow** [comment]
> А зачем ты сделал её public?

Да, проглядел

**Comment by Walter-Sparrow** [comment]
https://github.com/Walter-Sparrow/awesomeClicker/commit/e66047ba6d2e7b3dcc5ffb128441b4e23db51540
Исправил приватность
