### ISSUE TITLE
В данном случае не обязательно приводить к 2D вектору

### ISSUE THREAD

**Issue by Red-Cat-Fat** [Walter-Sparrow/awesomeClicker#2]
https://github.com/Walter-Sparrow/awesomeClicker/blob/3a429422949f4d7be3686787cb0832e9db941d6e/Assets/Scripts/ClickEvent.cs#L17-L19

**Comment by Walter-Sparrow** [comment]
https://github.com/Walter-Sparrow/awesomeClicker/commit/54d82208e259520493b412db1984ea51ece2e450
