### ISSUE TITLE
NRE

### ISSUE THREAD

**Issue by Red-Cat-Fat** [Walter-Sparrow/awesomeClicker#3]
https://github.com/Walter-Sparrow/awesomeClicker/blob/3a429422949f4d7be3686787cb0832e9db941d6e/Assets/Scripts/Plant.cs#L52

**Comment by Walter-Sparrow** [comment]
https://github.com/Walter-Sparrow/awesomeClicker/commit/d6fd6ffc4e10ee0dbdc56d2fa1967e6536a677c4
Не знаю, будет ли это грамотным решением проблемы?

**Comment by Walter-Sparrow** [comment]
Так же поправил несколько других скриптов, их можно посмотреть в ветке коммитов

**Comment by Red-Cat-Fat** [comment]
Ну как бы и да и нет. Вообще, если ты часто используешь какой-то компонент - нужно его брать и сохранять в соответствующую переменную и через неё работать. И уже эту переменную проверять на not null

**Comment by Walter-Sparrow** [comment]
https://github.com/Walter-Sparrow/awesomeClicker/commit/eb0d5e666e8d3639365ff55309e290053152a536
Вынес в отдельную переменную

**Comment by Walter-Sparrow** [comment]
https://github.com/Walter-Sparrow/awesomeClicker/issues/4
Есть вопрос, создал для него отдельный issue

**Comment by Red-Cat-Fat** [comment]
Я тебе говорю - нельзя так делать:
https://github.com/Walter-Sparrow/awesomeClicker/blob/eb0d5e666e8d3639365ff55309e290053152a536/Assets/Scripts/Plant.cs#L19
Ты сначала берёшь компонент, проверяешь его на null и только потом используешь его переменные, поля и свойства, вот как [тут](https://gist.github.com/Red-Cat-Fat/b0675928eeda60e833933957d53d4028).
Да, ты добавил RequireComponent, я понимаю, что он будет тут. Однако в будущем ты можешь сталкиваться с объектами, у которых нет этого компонента - поэтому настоятельно рекомендую использовать такую технику проверки.

**Comment by Walter-Sparrow** [comment]
https://github.com/Walter-Sparrow/awesomeClicker/commit/813cf031c331065a18d0b9e1b30b878543161c9c
Ну теперь точно все)

**Comment by Red-Cat-Fat** [comment]
Отписался в комите

**Comment by Walter-Sparrow** [comment]
https://github.com/Walter-Sparrow/awesomeClicker/commit/c5fc2cc4a4d7f019a502b615e689aa51505e29a0
Нейминг поменял, но второй пункт не понял;
Также есть коммиты для второго issue
