### ISSUE TITLE
Не знаю, как по-другому обращаться к объекту

### ISSUE THREAD

**Issue by Walter-Sparrow** [Walter-Sparrow/awesomeClicker#4]
https://github.com/Walter-Sparrow/awesomeClicker/blob/eb0d5e666e8d3639365ff55309e290053152a536/Assets/Scripts/Plant.cs#L18
Как можно исправить эту строку?

**Comment by Red-Cat-Fat** [comment]
Можно ссылкой прокидывать в этом месте:
https://github.com/Walter-Sparrow/awesomeClicker/blob/eb0d5e666e8d3639365ff55309e290053152a536/Assets/Scripts/Spawner.cs#L26
Instantiate возвращает GameObject, у которого ты можешь взять компонент Plant и в него прокинуть свой Spawner.
Но вообще вспомни что я говорил про паттерн "Observer" , там аналогичная механика работы.
Рекомендую почитать [эту статью](https://metanit.com/sharp/patterns/3.2.php)

**Comment by Walter-Sparrow** [comment]
https://github.com/Walter-Sparrow/awesomeClicker/commit/813cf031c331065a18d0b9e1b30b878543161c9c
https://github.com/Walter-Sparrow/awesomeClicker/commit/aec7809aa32a6824cf77c54b91d25985faae2426
Сделал обработку этих событий на UnityEventSystem
